### ISSUE TITLE
NuGet package is not up-to-date (1.0.0-pre02)

### ISSUE THREAD

**Issue by DavidMtbg** [blipson89/Leprechaun#16]
Hello, I would like to use the NuGet version of this to keep binaries out of source control, but it seems that the only version available there is over a year old and missing many of the great features that you've added.  I see that you have some scripts for packaging and pushing to NuGet - is it possibly an issue with these?

Thanks!

**Comment by blipson89** [comment]
Sorry about that! New packages are on their way up. NuGet is currently validating them, but `Leprechaun.Console.Runner` is the one you want, and that one appears to have completed validation. Latest version is `1.0.1-pre01`
