### ISSUE TITLE
Feature Request: Whitelisting for missing base templates

### ISSUE THREAD

**Issue by dreschner** [blipson89/Leprechaun#20]
In our solution, we sometimes use the standard rendering parameters item of sitecore as base templates. As this item comes from sitecore and defines some sitecore-internals, we don't want to serialize them.

Due to the missing serialization, we get the following message for all the items with the standard rendering parameters as base template:

> Unable to resolve base template 8ca06d6a-b353-44e8-bc31-b528c7306971. No fields from this template will exist.

This is somehow annoying, as a real missing item wouldn't stand out of all these messages. Therefore, it would be really cool to get a possibility to whitelist some missing base templates, so that only "real" missing templates will generate a warning.

**Comment by blipson89** [comment]
@dreschner 

I added a way of whitelisting in the latest version:

https://github.com/blipson89/Leprechaun/blob/master/src/Leprechaun.Console/Leprechaun.config#L106-L108
