### ISSUE TITLE
Missing binaries under assets for 1.1.1 release

### ISSUE THREAD

**Issue by wgrthoen** [blipson89/Leprechaun#30]
See title :)

**Comment by wgrthoen** [comment]
To quote Ben on Slack:

> **benlipson:leprechaun: 5:39 PM**
> interesting. i checked the analytics and saw that nobody was downloading the binaries, so i stopped. guess github analytics isn't flawless
> _`<snip>`_
> in the meantime, you can download the nuget package and open it in 7zip and grab the content folder
> _`<snip>`_
> https://www.nuget.org/api/v2/package/Leprechaun.Console.Runner/1.1.1

**Comment by blipson89** [comment]
@wgrthoen Fixed now - sorry about the delay
