### ISSUE TITLE
Exited with code 1

### ISSUE THREAD

**Issue by daivagna** [blipson89/Leprechaun#63]
I have installed leprechaun 2.2.2 but when i build my project it always comes up with an error “exited with code 1”

same configurations work in other project, its been long i am trying to figure but not sure what is the issue 

Configuration name in leprechaun config and module.json are same

same steps giving issues in other developer repo too and they are also facing same issue

what could be wrong?

**Comment by daivagna** [comment]
Hi @blipson89 

unfortunately it does not give any other error. Messages, even if i make the build out put to diagnostic, it just print outs “exited with code 1”

**Comment by daivagna** [comment]
Yes, i have hooked it on build event of VS studio

if i run it manually, it does not give any error not it creates model, its just shows leprechaun standard installation screen and comes back to a prompt 

if you can hop on a call for 2-5 mins can show you the set up

**Comment by blipson89** [comment]
I'm in the UTC-4 timezone. I'm available today and tomorrow after 10 am. Does that work for you?

**Comment by daivagna** [comment]
It seems it is around 03:30 pm IST, that works, my email is dnanavati@horizontal.com if you want send an imvite?

**Comment by blipson89** [comment]
3:30 PM IST is 6 AM for me. 

I'm available today right now for a few hours, or we can make some time tomorrow after 7 PM IST. I wrote down your email address, but would recommend you remove it from the previous comment, as this is a public repository and you may not want your email floating out there.

**Comment by daivagna** [comment]
Thank you, done, lets meet tomorrow

**Comment by daivagna** [comment]
Those who are looking for the solution it is at https://daivagnananavati.blogspot.com/2023/05/xm-cloud-sxastarter-kit-setting-up.html   @blipson89 and i connected and we agreed on this workaround
