### ISSUE TITLE
.NET 6 reaches end of life in Nov 2024 - .NET 8 support is required

### ISSUE THREAD

**Issue by peternazarov** [blipson89/Leprechaun#66]
.NET 6 reaches its end of support on November 12, 2024: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Currently, Leprechaun.Cli runs on .NET 6
https://github.com/blipson89/Leprechaun/blob/426f343dc9e2225be9bbaa6ae55a7fe924072b43/src/Leprechaun.Cli/Leprechaun.Cli.csproj#L10

It needs to be updated to .NET 8 asap so that developers can switch over their Sitecore solutions to .NET 8 in a timely manner before .NET 6 is out of support.

**Comment by blipson89** [comment]
@peternazarov just pushed up Leprechaun 2.2.5 which targets both .NET 6 and .NET 8.

I'm leaving .NET 6 as an _additional_ target for now until Microsoft drops support - just in case some people are a bit slower to update. 

Nuget is publishing now - should be live in an hour or two.

**Comment by peternazarov** [comment]
Perfect! Thank you, @blipson89
